services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web_jessie:
    build:
      context: .
    #  target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    # stop_signal: SIGINT
    ports:
      - '8000:8080'
    volumes:
      - .:/code
    depends_on:
      - redis
